# Generated by Django 4.2.3 on 2023-07-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapplication', '0003_profile_educational_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diplomas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='institutions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='numberofdiplomas',
            field=models.CharField(blank=True, choices=[('', 'Number Of Diploma/Degree Obtained'), ('1 ', '1'), ('2 ', '2'), ('2 ', '2'), ('3', '3'), ('more than 3', 'more than 3')], max_length=50, null=True),
        ),
    ]
