# Generated by Django 4.2.3 on 2023-07-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapplication', '0006_remove_profile_databases_remove_profile_frameworks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='diplomas',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='educational_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='institutions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='numberofdiplomas',
        ),
    ]
