# Generated by Django 4.2.3 on 2023-07-31 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formapplication', '0010_remove_profile_message1_remove_profile_message2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birthday'),
            preserve_default=False,
        ),
    ]
