# Generated by Django 4.2.3 on 2023-07-31 21:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formapplication', '0011_remove_profile_age_profile_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='other',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Laravel', 'Laravel'), ('Angular', 'Angular'), ('Django', 'Django'), ('Flask', 'Flask'), ('Vue', 'Vue'), ('Others', 'Others')], default='', max_length=50, null=True),
        ),
    ]
