# Generated by Django 4.2.3 on 2023-07-31 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formapplication', '0012_remove_profile_other_alter_profile_situation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='more_about_your_skills',
            field=models.TextField(blank=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
