# Generated by Django 4.2.3 on 2023-07-31 21:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formapplication', '0014_alter_profile_frameworks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='databases',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MySql', 'MySql'), ('Postgree', 'Postgree'), ('MongoDB', 'MongoDB'), ('Sqlite3', 'Sqlite3'), ('Oracle', 'Oracle'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Java', 'Java'), ('C++', 'C++'), ('Ruby', 'Ruby'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='libraires',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ajax', 'Ajax'), ('Jquery', 'Jquery'), ('Reactjs', 'Reactjs'), ('scikit-learn', 'scikit-learn'), ('TensorFlow', 'TensorFlow'), ('Others', 'Others')], default='', max_length=50),
        ),
    ]
